---
- name: AS
  hosts: AS1
  gather_facts: no

  tasks:
    - name: tao vlan
      ios_vlan:
        aggregate:
         - { vlan_id: 10, name: KeToan, interfaces: [Ethernet3/3] }
         - { vlan_id: 20, name: KyThuat, interfaces: [Ethernet3/2] }

    - name: show vlan
      ios_command:
        commands:
          - show vlan brief
      register: show_vlan

    - name: Set mode Trunking Vlan
      ios_config:
        lines:
          - spanning-tree mode rapid-pvst

    - name: chuyen cong e0/1 - e0/2 sang mode trunk
      ios_config:
        parents:
          - int range e0/1-2
        lines:
          - sw trunk en dot1Q
          - sw mode trunk

    - name: Show Trunking
      ios_command:
        commands:
        - show int trunk
      register: show_trunk

    - debug: var=show_ip.stdout_lines, var=show_trunk.stdout_lines
                                                                                
- name: AS
  hosts: AS2                                                                    
  gather_facts: no

  tasks:
    - name: tao vlan
      ios_vlan:
        aggregate:
         - { vlan_id: 10, name: KeToan, interfaces: [Ethernet3/2], delay: 5 }
         - { vlan_id: 20, name: Kythuat, interfaces: [Ethernet3/3], delay: 5 }

    - name: Show vlan
      ios_command:
        commands:
          - show vlan
      register: show_ip

    - name: config
      ios_config:
        lines:
          - spanning-tree mode rapid-pvst

    - name: chuyen cong e0/1 - e0/2 sang mode trunk
      ios_config:                                                               
        parents:                                                                
          - int range e0/1-2                                                    
        lines:
          - sw trunk en dot1Q                                                   
          - sw mode trunk

    - name: Show Trunking
      ios_command:
        commands:
        - show int trunk
      register: show_trunk

    - debug: var=show_ip.stdout_lines

