---
- name: DS
  hosts: DS
  gather_facts: no

  tasks:
    - name: tao vlan
      ios_vlan:
        aggregate:
          - { vlan_id : 10 }
          - { vlan_id : 20 }

    - name: Show vlan
      ios_command:
        commands:
          - show vlan

      register: show_ip
    - name: config
      ios_config:
        lines:
          - spanning-tree mode rapid-pvst

    - name: chuyen cong e0/1 - e0/3 sang mode trunk
      ios_config:
        parents:
          - int range e0/1-3
        lines:
          - sw trunk en dot1Q
          - sw mode trunk

    - debug: var=show_ip.stdout_lines

